logging:
  config: classpath:log4j2.yml

#pac4j:
#  clientName: shiro-cas-1
#
#shiro:
#  cas: http://www.demo.com
#  serverUrlPrefix: http://www.demo
#  loginUrl: ${shiro.serverUrlPrefix}/login?service=${shiro.serverUrlPrefix}/callback?client_name=${pac4j.clientName}


#cas配置
pac4j:
  client-name: mfgClient
  server:
    url: http://127.0.0.1:8080/cas
  project:
    url: http://127.0.0.1:8081
  filterChainDefinitionMap:
    "/": "securityFilter"
    "/index": "securityFilter"
    "/test": "anon"
    "/application/**": "securityFilter"
    "/callback": "callbackFilter"
    "/logout": "logout"
    "/**": "anon"
    #/user/edit/**: authc,perms[user:edit]


server:
  port: 8081
  server.servlet.context-path: /
  
# 数据库访问配置
spring:
  datasource: 
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.100.177:3306/els
    username: root
    password: 5Yg6f4x1%bDiX%Q*
    # 下面为连接池的补充设置，应用到上面所有数据源中
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM tbl_order
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小 
    #poolPreparedStatements: true
    #maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j2
    logSlowSql: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
  activiti:
    database-schema: create_drop
    check-process-definitions: false #关闭自动部署流程定义
    
    mailServerHost: smtp.qq.com
    mailServerUseSsl: true
    mailServerPort: 465
    mailServerUserName: 327370954@qq.com
    mailServerPassword: uhimbtjoxkrtbhba
    mailServerDefaultFrom: 327370954@qq.com

  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
    
mybatis:
  mapper-locations: classpath*:mybatis/*.xml
  configuration:
      map-underscore-to-camel-case: true
  type-aliases-package: com.springboot.activiti.model